---
title: "Subsetting the Gapminder Dataset for Intro, Session 2"
output: html_document
---

Read-in and write-out gapminder data in csv format

```{r}
load('data/gapminder.rdata')
write.csv(gapminder, file = "data/gapminder.csv", row.names = FALSE)
```


Create Asia and Africa subsets:

```{r}
africa <- subset(gapminder, continent == "Africa")
write.csv(africa, file="data/gapminder-africa-only.csv", row.names=FALSE)
```

To make the exercise "incovenient", reorder columns in the Asia data set:

```{r}
asia <- subset(gapminder, continent == "Asia")
asia <- asia[c("continent", "country", "year", "pop", "lifeExp", "gdpPercap")]
write.csv(asia, file="data/gapminder-asia-only.csv", row.names=FALSE)
```


## Subsetting by years instead:

```{r}
fifties.and.sixties <- subset(gapminder, year >= 1950 & year <=  1969)
write.csv(fifties.and.sixties, file="data/gapminder-fifties-and-sixties.csv", row.names=FALSE)
```

```{r}
seventies.and.eighties <- subset(gapminder, year >= 1970 & year <=  1989)
write.csv(seventies.and.eighties, file="data/gapminder-seventies-and-eighties.csv", row.names=FALSE)
```


To make the exercise "incovenient", reorder columns in the ninenties data set:

```{r}
nineties.and.later <- subset(gapminder, year >= 1990)
nineties.and.later <- nineties.and.later[c("continent", "country", "year", "pop", "lifeExp", "gdpPercap")]
write.csv(nineties.and.later, file="data/gapminder-nineties-and-later.csv", row.names=FALSE)
```













