---
title: 'Intro Session 1: Motivating reproducibility'
author: ''
date: ''
output:
  html_document:
    fig_height: 3
    fig_width: 6
---

## Welcome!

If you have not yet installed R and RStudio, and there is still some time until the workshop begins, please go ahead and do so now. Alternatively, you'll get a chance to do this over the coffee break as well.

**Download:** 

* *R*: You can download R from [CRAN](http://cran.r-project.org/), the Comprehensive R Archive Network. It is highly recommended to install a precompiled binary distribution for your operating system – use the links up at the top of the CRAN page.
* *RStudio*: You can download RStudio Desktop [here](http://www.rstudio.com/products/rstudio/download/).

**Install:** Instructions for installing R and RStudio are provided below, as well as links to videos that walk you through the process. Note newer versions of R and RStudio may have been released since this video, and hence the version names you come accross may not match what you see on the video. However the general instructions should still work.

Do not worry if you run into any trouble during the installation, we will have some time during the workshop to help you.

* Mac / OS X: 
    * [Video instructios](https://www.youtube.com/watch?v=Ywj6yNfc5nM) - includes RStudio installation
    * Instal R: Install R-3.2.0-mavericks.pkg. This runs on OS X 10.9 and later (Mavericks and Yosemite). To install, just double-click on the icon of the file you downloaded. See [here](http://cran.r-project.org/doc/manuals/r-release/R-admin.html#Installing-R-under-OS-X for) for more info.
    * Install RStudio: Double click on RStudio-0.98.1103.dmg and follow the prompts.
* PC / Windows: 
    * [Video instructios](https://www.youtube.com/watch?v=eD07NznguA4)
    * Install R: Installation is via the installer R-3.2.0-win.exe. Just double-click on the icon and follow the instructions. See [here](http://cran.r-project.org/doc/manuals/r-release/R-admin.html#Installing-R-under-Windows) for more info.
    * Install RStudio:Double click on RStudio-0.98.1103.exe and follow the prompts.
* Unix-alikes: See [here](http://cran.r-project.org/doc/manuals/r-release/R-admin.html#Installing-R-under-Unix_002dalikes) for more info. 

**Testing:** Do whatever is appropriate for your OS to launch RStudio. You should get a window similar to the screenshot you see in the video [here](http://www.rstudio.com/products/rstudio/). Put your cursor in the pane labelled *Console*, which is where you interact with the live R process. Create a simple object with code like `x <- 2 * 4` (followed by enter or return). Then inspect the `x` object by typing `x` followed by enter or return. Obviously you should see the value 8 print to screen. If yes, you are good to go.

**Add-on packages:** R is an extensible system and many people share useful code they have developed as a package via CRAN and github. To install a package from CRAN, for example the `ggplot2` package for data visualization (which we will use during the workshop) type `install.packages("ggplot2")` in your Console. This is one way of installing packages (there are others).

## Ex 1: Motivating reproducibility

**Part 1: Analyze + document**

Complete the following tasks and write instructions/documentation for your collaborator to reproduce your work starting with the original dataset. 

1. Visualize the relationship between life expectancy over time for Canada in the 1950s and 1960s using a line plot. (If you are quickly done with the main exercise and need something to fill your time with, you can work on the stretch goal below.)
    * Stretch goal: Add lines for Mexico and US.
  
2. Visualize the relationship between GDP and life expectancy for countries in Europe in the 1952.
    * Stretch goal: Add a line for 1967 in another color.

**Part 2: Swap + discuss**

- Introduce yourself to your collaborator and tell them why you're here.

- Swap instructions/documentation with your collaborator, and try to reproduce their work without talking to each oher. If your collaborator does not have the software they need to reproduce your work, we encourage you to either help them install it or walk them through it on your computer in a way that would emulate the experience.

- Then, talk to each other about challenges you faced (or didn't face) or why you were or weren't able to reproduce their work.
